export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAILED = 'LOGIN_ADMIN_FAILED';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_EMPLOYEE_FAILED = 'LOGIN_EMPLOYEE_FAILED';

export const Get_EMPLOYEE_DATA = 'Get_EMPLOYEE_DATA';
export const GET_EMPLOYEE_DATA_SUCCESS = 'GET_EMPLOYEE_DATA_SUCCESS';
export const Get_EMPLOYEE_DATA_FAILED = 'Get_EMPLOYEE_DATA_FAILED';

export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED';

export const SET_EDIT_MODE = 'SET_EDIT_MODE';

export const Get_REVIEWS_DATA = 'Get_REVIEWS_DATA';
export const GET_REVIEWS_DATA_SUCCESS = 'GET_REVIEWS_DATA_SUCCESS';
export const Get_REVIEWS_DATA_FAILED = 'Get_REVIEWS_DATA_FAILED';

export const SET_REVIEW_MODE = 'SET_REVIEW_MODE';

export const UPDATE_REVIEWS_SUCCESS = 'UPDATE_REVIEWS_SUCCESS';
export const UPDATE_REVIEWS_FAILED = 'UPDATE_REVIEWS_FAILED';


export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAILED = 'UPDATE_FEEDBACK_FAILED';
