export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAILED = 'LOGIN_ADMIN_FAILED';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_EMPLOYEE_FAILED = 'LOGIN_EMPLOYEE_FAILED';

export const Get_EMPLOYEE_DATA = 'Get_EMPLOYEE_DATA';
export const Get_EMPLOYEE_DATA_SUCCESS = 'Get_EMPLOYEE_DATA_SUCCESS';
export const Get_EMPLOYEE_DATA_FAILED = 'Get_EMPLOYEE_DATA_FAILED';
